/**
 * FrameDeck content catalog — Pack OS (look-operating systems)
 * Kit: Canon EOS M5 + EF-M 22mm f/2 STM
 * Differentiation: named looks, money frames, phone path, batch plans — not tip PDFs.
 */
import { SHOT_URIS } from "../shots/embeds.js";
import { resolveCheckout } from "./checkout-config.js";

export const CHECKOUT_SKUS = [
  "pack-neon-rain", "pack-golden-portrait", "pack-macro-dew", "pack-jazz-bar",
  "pack-action-freeze", "pack-blue-hour", "pack-boudoir", "pack-erotic-bw",
  "pack-raw-flash", "bundle-starter", "bundle-intimate", "bundle-all",
];

export const CHECKOUT = Object.fromEntries(
  CHECKOUT_SKUS.map((sku) => [sku, resolveCheckout(sku)])
);

export const BUNDLES = [
  { sku: "bundle-starter", title: "Starter week", packs: ["pack-neon-rain", "pack-golden-portrait", "pack-jazz-bar"], price: 29, blurb: "Three feed looks for a content week — neon, golden, tungsten." },
  { sku: "bundle-intimate", title: "Intimate week", packs: ["pack-boudoir", "pack-erotic-bw", "pack-raw-flash"], price: 49, blurb: "Boudoir + erotic B&W + raw flash diary. 18+ production OS.", nsfw: true },
  { sku: "bundle-all", title: "Full studio", packs: ["pack-neon-rain", "pack-golden-portrait", "pack-macro-dew", "pack-jazz-bar", "pack-action-freeze", "pack-blue-hour", "pack-boudoir", "pack-erotic-bw", "pack-raw-flash"], price: 89, blurb: "Every look-operating system unlocked.", nsfw: true },
];

export const SHOTS = [
  {
    id: "neon-rain",
    packSku: "pack-neon-rain",
    title: "Neon Rain Street",
    tag: "Night · Street",
    img: SHOT_URIS["5"],
    f: "f/2",
    iso: "3200",
    ss: "1/60",
    modes: ["Av or M", "WB: Tungsten/Custom", "Night mode OFF (phone)"],
    blurb: "Subscription-feed noir — wet asphalt, cyan/magenta neon, silhouette PPV energy.",
    explain: "Wide open at <strong>f/2</strong> so neon stays luminous without crushing shadows. <strong>1/60</strong> freezes light rain; pan slightly for streak drama. <strong>ISO 3200</strong> is the M5 night sweet spot. Expose for neon highlights; lift shadows in post. Dual Pixel AF on the silhouette edge.",
    nsfw: false,
    access: "paid",
    price: 15,
    albumReady: true,
    phonePath: "Lock exposure on the brightest neon. Turn OFF Night mode. Underexpose −0.7 so phones don’t blow signs. Shoot 4K then crop for posts.",
    avoid: ["Auto HDR (kills neon contrast)", "Warm Auto WB (muddies cyan/magenta)", "Focusing mid-street empty asphalt"],
    shootPlan: ["Min 0–2: Find reflective wet ground + one dominant neon color", "Min 2–5: Lock WB custom; set f/2, 1/60, ISO climb only as needed", "Min 5–10: Hero silhouette + 3 distance variants", "Min 10–15: Detail reflections + one candid walk-away"],
    contentBatch: "1 setup → 8 free feed posts + 3 PPV stills (silhouette series).",
    lightDiagram: "practical",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "neon-rain",
      count: 10,
      title: "Neon Rain · 10 money frames",
      note: "Feed-noir stills for night content weeks.",
    },
  },
  {
    id: "golden-portrait",
    packSku: "pack-golden-portrait",
    title: "Golden Hour Portrait",
    tag: "Portrait · Magic Hour",
    img: SHOT_URIS["1"],
    f: "f/2",
    iso: "200",
    ss: "1/500",
    modes: ["Av", "AF: Face+Tracking", "Meter: Spot face"],
    blurb: "Soft power face — intimate without full reveal; rim light that reads premium on a feed.",
    explain: "At ~35mm equiv., step in close. <strong>f/2</strong> separates subject with creamy falloff. <strong>1/500</strong> kills handshake in sun. <strong>ISO 100–200</strong>. Sun behind/side for rim; expose face (+0.3–0.7 if backlit).",
    nsfw: false,
    access: "free",
    price: 0,
    albumReady: true,
    phonePath: "Portrait mode optional; better: lock AE on face, step back, zoom 1.5–2× to flatten. Shoot into sun for free rim light.",
    avoid: ["Flat noon sun in front of face", "f/2 on 3/4 angle with both eyes soft", "Auto HDR washing skin"],
    shootPlan: ["Min 0–3: Place sun 45° behind shoulder", "Min 3–8: Face variants + eye-light from reflector (white shirt/wall)", "Min 8–12: Tease crop tighter", "Min 12–15: Environment + subject small in frame"],
    contentBatch: "1 golden hour → 6 feed posts + 2 PPV close-ups.",
    lightDiagram: "window",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "golden-portrait",
      count: 10,
      title: "Golden Portrait · 10 money frames",
      note: "Soft-power face & rim-light studies.",
    },
  },
  {
    id: "macro-dew",
    packSku: "pack-macro-dew",
    title: "Close Focus · Dew Macro",
    tag: "Macro · Detail",
    img: SHOT_URIS["4"],
    f: "f/5.6",
    iso: "400",
    ss: "1/200",
    modes: ["M or Av", "MF + peaking", "Timer"],
    blurb: "Detail filler content — between-PPV aesthetic posts that keep the grid expensive.",
    explain: "At <strong>0.15 m</strong> the 22mm gets dramatically close. Stop to <strong>f/5.6</strong> for usable DOF. <strong>1/200</strong> freezes leaf sway. Tripod or brace; rock focus.",
    nsfw: false,
    access: "paid",
    price: 12,
    albumReady: true,
    phonePath: "Use macro mode if available; tap to lock focus; burst 10 frames while rocking slightly. Crop hard in post.",
    avoid: ["f/2 at minimum focus (razor DOF miss)", "Handheld in wind", "Busy backgrounds fighting the drop"],
    shootPlan: ["Min 0–3: Find backlit droplets", "Min 3–10: Brace + focus stack by rocking body", "Min 10–15: Pull back for context detail frames"],
    contentBatch: "1 morning walk → 10 aesthetic fillers for slow content days.",
    lightDiagram: "window",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "macro-dew",
      count: 10,
      title: "Macro Dew · 10 money frames",
      note: "Detail/filler aesthetic for grid breathing room.",
    },
  },
  {
    id: "jazz-bar",
    packSku: "pack-jazz-bar",
    title: "Tungsten Jazz Bar",
    tag: "Interior · Low Light",
    img: SHOT_URIS["2"],
    f: "f/2",
    iso: "2500",
    ss: "1/50",
    modes: ["M", "WB: 2800–3200K", "Silent continuous"],
    blurb: "Tungsten seduction — hotel/club practicals, glass hero, transferable to any warm room.",
    explain: "Stay at <strong>f/2</strong>. <strong>1/50–1/60</strong> handheld floor. <strong>ISO 1600–3200</strong>. Custom WB for tungsten. Focus nearest glass edge.",
    nsfw: false,
    access: "paid",
    price: 15,
    albumReady: true,
    phonePath: "Disable Night mode. Lock AE on the practical bulb, then recompose. Slight underexposure keeps mood.",
    avoid: ["Auto WB (sickly green/magenta)", "Flash destroying tungsten mood", "Focusing background band instead of glass"],
    shootPlan: ["Min 0–3: One practical as key (lamp/sconce)", "Min 3–8: Glass/hero prop foreground", "Min 8–12: Subject half-lit portraits", "Min 12–15: Wide environment establishing"],
    contentBatch: "1 room setup → 5 moody feed posts + 4 PPV warm portraits.",
    lightDiagram: "practical",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "jazz-bar",
      count: 10,
      title: "Jazz Bar · 10 money frames",
      note: "Warm practical-light intimacy transferable to hotel rooms.",
    },
  },
  {
    id: "action-freeze",
    packSku: "pack-action-freeze",
    title: "Urban Action Freeze",
    tag: "Action · Daylight",
    img: SHOT_URIS["6"],
    f: "f/4",
    iso: "400",
    ss: "1/1600",
    modes: ["Tv / S", "AF: Servo", "High burst"],
    blurb: "Energy lifestyle batch — movement as brand for fitness-adjacent creators.",
    explain: "Shutter first: <strong>1/1000–1/2000</strong>. <strong>f/4</strong> for tracking DOF. <strong>ISO 200–400</strong> midday. Low angle + 22mm FOV.",
    nsfw: false,
    access: "paid",
    price: 12,
    albumReady: true,
    phonePath: "Action mode / burst. Tap subject, lock AE. Prefer bright sun; avoid digital zoom.",
    avoid: ["1/250 on airborne subjects", "Center framing only", "Missing the peak moment (shoot bursts)"],
    shootPlan: ["Min 0–3: Pre-focus landing zone", "Min 3–12: Burst through 5–8 actions", "Min 12–15: Hero low-angle stills"],
    contentBatch: "1 session → 12 Reels stills + 3 feed heroes.",
    lightDiagram: "window",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "action-freeze",
      count: 10,
      title: "Action Freeze · 10 money frames",
      note: "Motion energy for lifestyle branding.",
    },
  },
  {
    id: "blue-hour-land",
    packSku: "pack-blue-hour",
    title: "Blue Hour Landscape",
    tag: "Landscape · Deep Focus",
    img: SHOT_URIS["3"],
    f: "f/8",
    iso: "200",
    ss: "1/30",
    modes: ["M or Av", "Tripod", "2s timer"],
    blurb: "Cinematic establishing — location branding for travel and creative profiles.",
    explain: "<strong>f/8</strong> near-to-far. Tripod; <strong>ISO 200–400</strong>; <strong>1/15–1/60</strong>. Hyperfocal focus.",
    nsfw: false,
    access: "free",
    price: 0,
    albumReady: true,
    phonePath: "Night mode on tripod/ledge only; otherwise lock exposure darker for blue. Shoot RAW if available.",
    avoid: ["Handheld long shutter", "Auto boost killing blue hour color", "No foreground anchor"],
    shootPlan: ["Min 0–5: Arrive before blue; compose layers", "Min 5–12: Bracket exposures", "Min 12–15: Detail foreground textures"],
    contentBatch: "1 location → 4 feed establishers + 1 carousel story.",
    lightDiagram: "window",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "blue-hour",
      count: 10,
      title: "Blue Hour · 10 money frames",
      note: "Establishing frames for location-branded grids.",
    },
  },
  {
    id: "boudoir-soft",
    packSku: "pack-boudoir",
    title: "Boudoir Soft Light",
    tag: "Boudoir · Intimate",
    img: SHOT_URIS["7"],
    f: "f/2",
    iso: "800",
    ss: "1/160",
    modes: ["Av or M", "AF: Face+Tracking", "WB: Cloudy 5600–6000K"],
    blurb: "Paid intimacy OS — window light, fabric hierarchy, money angles, comfort-first direction.",
    explain: "Large window + sheer = free softbox. <strong>f/2</strong> for intimacy falloff; ~35mm FOV for environmental closeness. <strong>1/160–1/200</strong>. <strong>ISO 400–1600</strong>. Expose skin highlights. Consent and warmth > gear.",
    nsfw: true,
    access: "paid",
    price: 19,
    albumReady: true,
    phonePath: "Face the window; phone between you and window for soft front light. Portrait mode sparingly. Lock AE on skin highlight.",
    avoid: ["Overhead ceiling-only light (raccoon eyes)", "Cold blue WB on skin", "Rushing poses — hold 3 breaths per frame", "Cluttered backgrounds fighting the subject"],
    shootPlan: ["Min 0–3: Clear clutter; sheer on window; set white balance cloudy", "Min 3–6: Hero face + shoulder (PPV cover)", "Min 6–10: Form frames mid-distance; fabric hierarchy (sheet vs skin)", "Min 10–13: Detail hands/jewelry/fabric", "Min 13–15: Environment wide + one candid laugh"],
    contentBatch: "1 window setup → 6 free teasers + 6 PPV stills + 1 detail carousel.",
    lightDiagram: "window",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "boudoir",
      count: 10,
      title: "Boudoir · 10 money frames",
      note: "Intimate production stills — soft power, not clinical.",
    },
  },
  {
    id: "erotic-bw",
    packSku: "pack-erotic-bw",
    title: "Erotic Black & White",
    tag: "Fine Art · Monochrome",
    img: SHOT_URIS["8"],
    f: "f/2.8",
    iso: "1600",
    ss: "1/125",
    modes: ["M", "Picture Style: Monochrome", "Spot meter highlight"],
    blurb: "Art-porn hybrid — contrast as brand; form over explicit; gallery-grade for premium tiers.",
    explain: "Shape and light, not color. Single side-light. <strong>f/2.8–f/4</strong> for form. <strong>1/125</strong>. <strong>ISO 800–3200</strong> for grain. Meter brightest skin/sheet; let blacks fall.",
    nsfw: true,
    access: "paid",
    price: 19,
    albumReady: true,
    phonePath: "Shoot color RAW/HEIF then mono in edit (more control). Expose for highlights. Add grain deliberately.",
    avoid: ["Flat even light (no sculpture)", "Muddy midtone-only histograms", "Over-sharpening skin in mono", "Color distractions before conversion"],
    shootPlan: ["Min 0–3: One hard or window side light; kill fill", "Min 3–8: Form frames — curves, negative space", "Min 8–12: Detail (hands, collarbone, fabric folds)", "Min 12–15: Abstract crop that still reads as intentional art"],
    contentBatch: "1 contrast setup → 4 premium PPV + 4 art-feed posts (safe-for-main-grid if cropped).",
    lightDiagram: "window",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "erotic-bw",
      count: 10,
      title: "Erotic B&W · 10 money frames",
      note: "Chiaroscuro form studies for premium grids.",
    },
  },
  {
    id: "raw-flash",
    packSku: "pack-raw-flash",
    title: "Raw Flash Editorial",
    tag: "Flash · Diary",
    img: SHOT_URIS["9"],
    f: "f/5.6",
    iso: "200",
    ss: "1/200",
    modes: ["M", "Flash: Direct on-camera", "WB: Flash 5500K"],
    blurb: "Diary aesthetic franchise — white wall, hard flash, anti-studio authenticity audiences trust.",
    explain: "Shutter at <strong>1/200</strong> (X-sync). <strong>f/5.6–f/8</strong>. <strong>ISO 100–400</strong>. Direct flash owns the frame. Hard wall shadow is the brand. Stand close with 22mm. Consent is non-negotiable — the look feels invasive if the vibe isn’t mutual.",
    nsfw: true,
    access: "paid",
    price: 19,
    albumReady: true,
    phonePath: "Use screen/torch only as weak fill; better: cheap mini flash or continuous LED close + high contrast edit. Or screenshot-vibe: hard room light + exposure lock down.",
    avoid: ["Bouncing flash (kills the diary hard shadow)", "ISO 3200 instead of flash power (noisy, soft look)", "Standing too far (loses confrontational 35mm energy)", "Apologetic posing — commit to the stare"],
    shootPlan: ["Min 0–2: White/neutral wall; kill ambient (darker room)", "Min 2–4: M mode 1/200 · f/5.6 · ISO 200; test flash power for skin without blinkies", "Min 4–9: Hero stare + 3 distance steps (close/medium/lean)", "Min 9–12: Detail (jewelry, waistband, texture) with same flash", "Min 12–15: Candid laugh + one ‘almost failed’ frame for authenticity"],
    contentBatch: "1 wall + flash → 10 diary posts across a week (series continuity) + 3 PPV hard-flash sets.",
    lightDiagram: "flash",
    frameRoles: [
      { role: "Hero", use: "Cover / PPV thumbnail" },
      { role: "Tease", use: "Free feed scroll-stop" },
      { role: "Tease 2", use: "Story / teaser carousel" },
      { role: "Form", use: "Paid mid-tier frame" },
      { role: "Form 2", use: "Angle variant for batch" },
      { role: "Detail", use: "Aesthetic filler post" },
      { role: "Environment", use: "Story / location beat" },
      { role: "Expression", use: "Face/mood variant" },
      { role: "Drama", use: "High-contrast hero alt" },
      { role: "Candid", use: "Authenticity / diary beat" }
    ],
    album: {
      folder: "raw-flash",
      count: 10,
      title: "Raw Flash Diary · 10 money frames",
      note: "White-wall flash system for diary-authentic feeds.",
    },
  },
];
